account/urls.py
from django.urls import path, include
from django.urls.resolvers import URLPattern
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from awesomesite.settings import MEDIA_ROOT
from . import views

app_name = 'account'

urlpatterns = [
    #post views
    path('login/',views.user_login,name='login'),

    #authentication views
    # path('login/',auth_views.LoginView.as_view(), name='login'), i am not using this
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),

    #change password urls
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    #reset password urls
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    # path('reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_complete'),

    #Instead of all that i wrote at the top I can just use this 
    # path('', include('django.contrib.auth.urls')),

    #home page
    path('',views.dashboard,name='dashboard'),
    #others
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    
    # people
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

awesomesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.conf import settings
from awesomesite.settings import MEDIA_ROOT
from django.contrib.auth import views as auth_views

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    path('',include('portfolio.urls',namespace='portfolio')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    # social authentication
    path('social-auth/',include('social_django.urls', namespace='social')),

    # authentication url
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_complete'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

    # images url
    path('images/', include('images.urls', namespace='images')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('',views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    # path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share',views.post_share,name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('feed/',LatestPostsFeed(),name='post_feed')

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index_page'),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.


def index(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        sender = request.POST.get("email")
        body = request.POST.get('message')

        send_mail(
            subject=f"From {name}",
            message=f"Sender: {sender}\n\n{body}",
            from_email= settings.DEFAULT_FROM_EMAIL,
            recipient_list=["femimathias39@gmail.com",]
        )     

    return render(request, 'portfolio/index.html')

portfolio/templates/portfolio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Dickson's Portfolio</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" href="{% static 'portfolio/images/favicon.ico' %}" type="image/x-icon">  
    <link rel="stylesheet" href="{% static 'portfolio/assets/css/main.css' %}" />
  </head>
  <body class="is-preload">
    <!-- Header -->
    <div class="header">
      <div class="top">
        <!-- Logo -->
        <div id="logo">
          <span class="image avatar48"
            ><img src="{% static 'portfolio/images/avatar.PNG' %}" alt=""
          /></span>
          <h1 id="title">Dickson Durosakin</h1>
          <p>Python Developer</p>
        </div>

        <!-- Nav -->
        <nav id="nav">
          <ul>
            <li>
              <a href="#top" id="top-link"
                ><span class="icon solid fa-home">Intro</span></a
              >
            </li>
            <li>
              <a href="#portfolio" id="portfolio-link"
                ><span class="icon solid fa-th">Portfolio</span></a
              >
            </li>
            <li>
              <a href="{% url 'account:dashboard'%}" id="about-link"
                ><span class="icon solid fa-user">Bookmarks App</span></a
              >
            </li>
            <li>
              <a href="{% url 'blog:post_list'  %}" id="contact-link"
                ><span class="icon solid fa-envelope">My blog</span></a
              >
            </li>
          </ul>
        </nav>
       
      </div>



      <div class="bottom">
        <!-- Social Icons -->
        <ul class="icons">
          <li>
            <a href="https://twitter.com/ddon375" class="icon brands fa-twitter"
              ><span class="label">Twitter</span></a
            >
          </li>
          <li>
            <a
              href="https://www.facebook.com/dickson.durosakin.1/"
              class="icon brands fa-facebook-f"
              ><span class="label">Facebook</span></a
            >
          </li>
          <li>
            <a
              href="https://github.com/dicksondurosakin"
              class="icon brands fa-github"
              ><span class="label">Github</span></a
            >
          </li>
          <li>
            <a
              href="mailto: durosakindickson@gmail.com"
              class="icon solid fa-envelope"
              ><span class="label">Email</span></a
            >
          </li>
        </ul>
      </div>
    </div>

    <!-- Main -->
    <div id="main">
      <!-- Intro -->
      <section id="top" class="one dark cover">

        <div class="hamburger">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
        </div>


        <div class="container">
          <header>
            <h2 class="alt">
              Hi! I'm <strong>Dickson</strong>, a Python Developer<br />
              and a Coding Instructor.
            </h2>
            <p>
              I use Python Django Framework to make the backend of Websites.<br />
              My goal is to make people's lives better through my coding
              knowledge
            </p>
          </header>

          <footer>
            <a href="#portfolio" class="button scrolly">Portfolio</a>
          </footer>
        </div>
      </section>

      <!-- Portfolio -->
      <section id="portfolio" class="two">
        <div class="container">
          <header>
            <h2>Portfolio</h2>
          </header>

          <p>Here are some of the projects I have worked on.</p>

          <div class="row">
            <div class="col-4 col-12-mobile">
              <article class="item">
                <img
                  class="image fit"
                  src="{% static 'portfolio/images/devsearch.PNG'%}"
                  alt="devsearch"
                />
                <header>
                  <a href="https://searchdevelopers.herokuapp.com/"
                    ><h3>Devsearch</h3></a
                  >
                </header>
              </article>
            </div>
            <div class="col-4 col-12-mobile">
              <article class="item">
                <img
                  class="image fit"
                  src="{% static 'portfolio/images/tech-diversity.PNG'%}"
                  alt="tech-diversity"
                />
                <header>
                  <a href="https://dicksondurosakin.github.io/Tech_Diversity/"
                    ><h3>Tech Diversity</h3></a
                  >
                </header>
              </article>
            </div>
            <div class="col-4 col-12-mobile">
              <article class="item">
                <img
                  class="image fit"
                  src="{% static 'portfolio/images/loan-website.PNG' %}"
                  alt="loan-website"
                />
                <header>
                  <a href="http://loanwebpage.herokuapp.com/"
                    ><h3>Loan Website</h3></a
                  >
                </header>
              </article>
            </div>
          </div>
        </div>
      </section>

      <!-- About Me -->
      <section id="about" class="three">
        <div class="container">
          <header>
            <h2>About Me</h2>
          </header>

          <img
            class="image featured"
            src="{% static 'portfolio/images/avatar.PNG' %}"
            alt="Dickson's Image"
          />

          <p>
            I started my coding journey in January of 2021, back then i was
            trying to find a way to build a reminder application into an Excel
            spreadsheet. After failing to do that using Excel that I knew, I
            decided that the best thing was to learn to code. I'm glad I took
            that step that month because ever since then I haven't stopped
            coding. I got an Internship at
            <a href="https:www.instincthub.com">InstinctHub </a>in April of the
            same year that extended into a full time offer after 6 months. At
            <a href="https:www.instincthub.com">InstinctHub </a> I teach coding
            skills, my courses are available at
            <a href="https://skills.instincthub.com/">Skills.instincthub.com</a>
            <br />When I am not making websites or teaching someone coding
            skills I am either watching movies, learning or reading.
          </p>
        </div>
      </section>

      <!-- Contact -->
      <section id="contact" class="four">
        <div class="container">
          <header>
            <h2>Contact</h2>
          </header>

          <p>
            Want to reach me for opportunities or just want to have a chat, feel
            free to send me a message here
          </p>

          <form method="post" action="{% url 'portfolio:index_page' %}">
            {% csrf_token %}
            <div class="row">
              <div class="col-6 col-12-mobile">
                <input
                  type="text"
                  name="name"
                  placeholder="Name"
                  value="name"
                />
              </div>
              <div class="col-6 col-12-mobile">
                <input
                  type="text"
                  name="email"
                  placeholder="Email"
                  value="email"
                />
              </div>
              <div class="col-12">
                <textarea
                  name="message"
                  placeholder="Message"
                  value="message"
                ></textarea>
              </div>
              <div class="col-12">
                <input type="submit" value="Send Message" />
              </div>
            </div>
          </form>
          <video src="https://www.youtube.com/watch?v=wvhP1al3Ur4"></video>
        </div>
      </section>
    </div>

    <!-- Scripts -->
    <script src="{% static 'portfolio/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/browser.min.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/util.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/main.js' %}"></script>
    <script src="{% static 'portfolio/assets/js/hamburger.js' %}"></script>
  </body>
</html>