account/urls.py
from django.urls import path, include
from django.urls.resolvers import URLPattern
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from awesomesite.settings import MEDIA_ROOT
from . import views

app_name = 'account'

urlpatterns = [
    #post views
    path('login/',views.user_login,name='login'),

    #authentication views
    # path('login/',auth_views.LoginView.as_view(), name='login'), i am not using this
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),

    #change password urls
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    #reset password urls
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    # path('reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_complete'),

    #Instead of all that i wrote at the top I can just use this 
    # path('', include('django.contrib.auth.urls')),

    #home page
    path('',views.dashboard,name='dashboard'),
    #others
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    
    # people
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

awesomesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.conf import settings
from awesomesite.settings import MEDIA_ROOT
from django.contrib.auth import views as auth_views

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    path('',include('portfolio.urls',namespace='portfolio')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    # social authentication
    path('social-auth/',include('social_django.urls', namespace='social')),

    # authentication url
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_complete'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

    # images url
    path('images/', include('images.urls', namespace='images')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('',views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    # path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share',views.post_share,name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('feed/',LatestPostsFeed(),name='post_feed')

]

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/',views.image_create,name='create'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('',views.image_list,name='list')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index_page'),
]

images/models.py
from email.policy import default
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='images_created',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to = 'images/%Y/%m/%d/',)
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveBigIntegerField(db_index=True,default=0)
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title','url','description')
        widgets = {
            'url':forms.HiddenInput,
        }
    
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg','jpeg']
        extension = url.rsplit('.',1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match'\
                                        'valid image extensions.')
        return url
    
    def save(self,force_insert=False,
                force_update=False,
                commit = True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'

        # download image from the given url
        response = request.urlopen(image.url)
        image.image.save(image_name,ContentFile(response.read()),save=False)

        if commit:
            image.save()
        
        return image

images/views.py
from re import L
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from common.decorators import ajax_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.decorators.http import require_POST
from actions.utils import create_action

# is ajax has been deprecated so I will create my own
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


# Create your views here.
@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)

            # assign current user to the item
            new_item.user = request.user
            new_item.save()
            create_action(request.user,'bookmarked image',new_item)
            messages.success(request,'Image added successfully')

            # redirect to the created item detail view
            return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html',
                                {'section': 'images',
                                'form': form})

def image_detail(request,id,slug):
    image = get_object_or_404(Image,id=id,slug=slug)
    return render(request,'images/image/detail.html',{
                                            'section':'images',
                                            'image':image})

@login_required
@require_POST
@ajax_required
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})


@login_required
def image_list(request):
    images = Image.objects.all()
    # result per page
    paginator = Paginator(images,8)
    # what page is the request asking for
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # if not page was passed to the request return first page
        images = paginator.page(1)
    except EmptyPage:
        if is_ajax(request):
            # if ajax and theres nothing on next page:
            return HttpResponse('')
        # if its normal request
        images = paginator.page(paginator.num_pages)
    if is_ajax(request):
        return render(request,'images/image/list_ajax.html',
                                {'section':'images',
                                'images':images})
    return render(request,'images/image/list.html',
                                {'section':'images',
                                'images':images})

images/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static 'images/css/base.css' %}" rel="stylesheet">
</head>
<body>
 <div id="header">
 <span class="logo">Bookmarks</span>
 {% if request.user.is_authenticated %}
 <ul class="menu">
 <li {% if section == "dashboard" %}class="selected"{% endif %}>
 <a href="{% url 'account:dashboard' %}">My dashboard</a>
 </li>
 <li {% if section == "images" %}class="selected"{% endif %}>
 <a href="#">Images</a>
 </li>
 <li {% if section == "people" %}class="selected"{% endif %}>
 <a href="#">People</a>
 </li>
 </ul>



 {% endif %}
 <span class="user">
 {% if request.user.is_authenticated %}
 Hello {{ request.user.first_name|title }},
 <a href="{% url 'account:logout' %}">Logout</a>
 {% else %}
 <a href="{% url 'account:login' %}">Log-in</a>
 {% endif %}
 </span>
 </div>
 {% if messages %}
 <ul class="messages">
 {% for message in messages %}
 <li class="{{ message.tags }}">
 {{ message|safe }}
 <a href="#" class="close">x</a>
 </li>
 {% endfor %}
 </ul>
{% endif %}

 <div id="content">
 {% block content %}
 {% endblock %}
 <br><br>
 <a href="{% url 'portfolio:index_page' %}">My Portfolio</a>
 </div>
</body>
<span>my name is Dickson</span>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>
 var csrftoken = Cookies.get('csrftoken');
 function csrfSafeMethod(method) {
 // these HTTP methods do not require CSRF protection
 return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
 }
 $.ajaxSetup({
 beforeSend: function(xhr, settings) {
 if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
 xhr.setRequestHeader("X-CSRFToken", csrftoken);
 }
 }
 });
 $(document).ready(function(){
    console.log('free')
    {% block domready %}
    {% endblock %}
    console.log('dom')
 });
</script>
</html>

images/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">  
 <link href="{% static 'images/css/base.css' %}" rel="stylesheet">
</head>
<body>
 <div id="header">
 <span class="logo">Bookmarks</span>
 {% if request.user.is_authenticated %}
 <ul class="menu">
 <li {% if section == "dashboard" %}class="selected"{% endif %}>
 <a href="{% url 'account:dashboard' %}">My dashboard</a>
 </li>
 <li {% if section == "images" %}class="selected"{% endif %}>
   <a href="{% url 'images:list' %}">Images</a>
  </li>
  <li {% if section == "people" %}class="selected"{% endif %}>
   <a href="{% url 'account:user_list' %}">People</a>
  </li>
 </ul>



 {% endif %}
 <span class="user">
 {% if request.user.is_authenticated %}
 Hello {{ request.user.first_name|title }},
 <a href="{% url 'account:logout' %}">Logout</a>
 {% else %}
 <a href="{% url 'account:login' %}">Log-in</a>
 {% endif %}
 </span>
 </div>
 {% if messages %}
 <ul class="messages">
 {% for message in messages %}
 <li class="{{ message.tags }}">
 {{ message|safe }}
 <a href="#" class="close">x</a>
 </li>
 {% endfor %}
 </ul>
{% endif %}

 <div id="content">
 {% block content %}
 {% endblock %}
 <br><br>
 <a href="{% url 'portfolio:index_page' %}">My Portfolio</a>
 </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>
 var csrftoken = Cookies.get('csrftoken');
 function csrfSafeMethod(method) {
 // these HTTP methods do not require CSRF protection
 return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
 }
 $.ajaxSetup({
 beforeSend: function(xhr, settings) {
 if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
 xhr.setRequestHeader("X-CSRFToken", csrftoken);
 }
 }
 });
 $(document).ready(function(){
    {% block domready %}
    {% endblock %}
 });
</script>
</html>