awesomesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.conf import settings
from awesomesite.settings import MEDIA_ROOT
from django.contrib.auth import views as auth_views

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    path('',include('portfolio.urls',namespace='portfolio')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    # social authentication
    path('social-auth/',include('social_django.urls', namespace='social')),

    # authentication url
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_complete'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

    # images url
    path('images/', include('images.urls', namespace='images')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('',views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    # path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share',views.post_share,name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('feed/',LatestPostsFeed(),name='post_feed')

]

blog/models.py
from typing import Match
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField, EmailField
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager() #default manager
    published = PublishedManager() #our custom manager

    def get_absolute_url(self):
        return reverse('blog:post_detail',
        args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Page, Paginator,EmptyPage,PageNotAnInteger
import os
import sys

#emails
from django.core.mail import send_mail
from django.conf import settings

from .forms import EmailPostForm,CommentForm,SearchForm
from .models import Post,Comment
from django.db.models import Count
from django.views.generic import ListView

# tagit
from taggit.models import Tag
# postgres
from django.db.models import Q
from django.db.models.functions import Greatest
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank,TrigramSimilarity

# Create your views here.

# class base view of post list. This code is so short but does the same thing as the function based view
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

# function based view of post list
def post_list(request, tag_slug = None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list,3)# 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #if page is out of range deliver the last page of result
        posts = paginator.page(paginator.num_pages) 
    return render(request, 'blog/post/list.html',{'posts':posts,'tag':tag,'page':page})

def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    
    # list of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == "POST":
        # A new post was added 
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            # create a new comment object but don't save to the database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            # save the comment
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # print(similar_posts)
    # annotate is like give me every distinct value in this queryset
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]



    return render(request, 'blog/post/detail.html',{'post':post,
                                                    'comments':comments,
                                                    'new_comment':new_comment,
                                                    'comment_form':comment_form,
                                                    'similar_posts':similar_posts})

def post_share(request,post_id):
    #retrieve post by id
    post = get_object_or_404(Post,id=post_id,status='published')
    sent = False
    if request.method == 'POST':
        #form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
            # # send mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            name = cd['name']
            receiver = cd['to']

            send_mail(
                subject=f"{name} recommends you read {post.title}",
                message="to you",
                html_message = f"Read {post.title} at <a href='{post_url}'>this link<a> <br><br>" \
                            f"{cd['name']}\'s comments: {cd['comments']}",
                from_email= settings.DEFAULT_FROM_EMAIL,
                recipient_list=[receiver,]
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        # Search according to 
        if form.is_valid():
            query = form.cleaned_data['query']
        try:
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.01).order_by('-rank')
            if results < 1:
                raise Exception("NotEnough")
        except:
            results = Post.published.filter(Q(title__icontains=query)|Q(body__icontains=query)).reverse()
        
        paginator = Paginator(results,3)# 3 posts in each page
        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            #if page is not an integer deliver the first page
            results = paginator.page(1)
        except EmptyPage:
            #if page is out of range deliver the last page of result
            results = paginator.page(paginator.num_pages)
    return render(request,'blog/post/search.html',{'form':form,'query':query,'results':results,})

blog/templates/blog/post/detail.html
{% extends 'blog/base.html'%} {%load blog_tags%} {% block title %}{{post.title}}
{%endblock%}
<!-- the block tags must not be divided -->
{% block content %}
<h1>{{post.title}}</h1>
<p class="date">published {{post.publish}} by {{post.author}}</p>
{{post.body|markdown}}
<p>
  <a href="{% url 'blog:post_share' post.id %}">share this post</a>
</p>
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %} There are no similar posts yet. {% endfor %}

<!-- Comment Count -->
{% with comments.count as total_comments %}
<h2>{{total_comments}} comment{{total_comments|pluralize}}</h2>
{% endwith %}
<!-- peoples comment -->
{% for comment in comments %}
<div class="comment">
  <p class="info">
    Comment {{forloop.counter}} by {{comment.name}} {{comment.created}}
  </p>
  {{comment.body|linebreaks}}
</div>
<!--  -->
{% empty %}
<p>There are no comments yet</p>
{% endfor %}
<br />
{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form method="post">
  {{ comment_form.as_p }} {% csrf_token %}
  <p><input type="submit" value="Add comment" /></p>
</form>
{% endif %}
<!--The block tags must not be divided  -->
{%endblock%}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts%}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %} {% load blog_tags %}
<!--  -->
{% block title %} My Blog{% endblock %}
<!-- The block tags are important  -->
{% block content %}
<h1>My Blog</h1>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
<!--  -->
{% for post in posts %}
<h2>
  <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
</h2>
<p class="tags">
  Tags: {% for tag in post.tags.all %}
  <a href="{% url 'blog:post_list_by_tag' tag.slug %}"> {{ tag.name }} </a>
  {% if not forloop.last %}, {% endif %} {% endfor %}
</p>
<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
{{ post.body|only_text|truncatewords:15 }}
<!-- <h2>Similar posts</h2>
{% for similar in post.tags.similar_objects %}
<p>
  <a href="{{ similar.get_absolute_url }}">{{ similar.title }}</a>
</p>
{% empty %} There are no similar posts yet. {% endfor %}  -->

{% endfor %}
<!--  -->
{% include 'pagination.html' with page=posts %}
<!-- This next line is important -->
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search {% endblock %}
{% block content%}
{% if query %}
<h1>Posts containing "{{query}}"</h1>
<h3>
    {%with results.count as total_results %}
    Found {{total_results}} result{{total_results|pluralize}}
    {%endwith%}
</h3>
{% for post in results %}
<h4><a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>
{{post.body|markdown|truncatewords:5}}
{%empty%}
<p>There is no result for your query</p>
{%endfor%}

{% include 'pagination.html' with page=results query=query %}
<p><a href="{% url 'blog:post_search'%}">Search again</a></p>
{%else%}
<h1>Search for posts</h1>
<form action="" method="get">
    {{form.as_p}}
<input type="submit" value="Search">
</form>
{%endif%}
{%endblock%}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %} {% block title %}Share a post{% endblock %}
<!--  -->
{% block content %} {% if sent %}
<h1>E-mail successfully sent</h1>
<p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
  {{ form.as_p }} {% csrf_token %}
  <input type="submit" value="Send e-mail" />
</form>
{% endif %} {% endblock %}